name: Dispatch Push Event

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: pizzamx/pizzamx.github.io
          token: ${{ secrets.PAT_FOR_ACTIONS }}
          event-type: my-push-event
          client-payload: '{"ref": "${{ github.sha }}"}'
